language: node_js
node_js:
  - "8"

script:
  - yarn test
  - yarn build
  - npx jest --coverage && cat ./coverage/lcov.info | npx coveralls && rm -rf ./coverage

cache:
  yarn: true
  directories:
    - node_modules
